Resources:
  DeliveryStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Table that contains data necessary to check the status of delivery to a recipient"
      - Key: VantaContainsUserData
        Value: false
Outputs:
  DeliveryStatusTableArn:
    Export:
      Name: backend-${self:custom.stage}-DeliveryStatusTableArn
    Value:
      Fn::GetAtt: [DeliveryStatusTable, Arn]
  DeliveryStatusTableName:
    Export:
      Name: backend-${self:custom.stage}-DeliveryStatusTableName
    Value:
      Ref: DeliveryStatusTable
