Resources:
  EventLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: tenantId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ByMessageId
          KeySchema:
            - AttributeName: messageId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Stores logs of API requests sent to Courier."
      - Key: VantaContainsUserData
        Value: false
      - Key: tags.courier.com/service
        Value: pipeline
Outputs:
  EventLogsTableName:
    Export:
      Name: backend-${self:custom.stage}-EventLogsTableName
    Value:
      Ref: EventLogsTable
  EventLogsTableArn:
    Export:
      Name: backend-${self:custom.stage}-EventLogsTableArn
    Value:
      Fn::GetAtt: [EventLogsTable, Arn]
