Resources:
  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: lockKey
          AttributeType: S
        - AttributeName: purpose
          AttributeType: S
      KeySchema:
        - AttributeName: lockKey
          KeyType: HASH
        - AttributeName: purpose
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "General purpose Lock table that can be leveraged to prevent data duplication during feature rollouts"
      - Key: VantaContainsUserData
        Value: false # true if contains user data
