Resources:
  SessionManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: namespace
          AttributeType: S
      KeySchema:
        - AttributeName: namespace
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Session metadata used to invalidate user sessions"
      - Key: VantaContainsUserData
        Value: false
Outputs:
  SessionManagementTable:
    Export:
      Name: backend-${self:custom.stage}-SessionManagementTable
    Value:
      Ref: SessionManagementTable
