Resources:
  TenantMetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: updated
          AttributeType: N
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: by-updated-index
          KeySchema:
            - AttributeName: updated
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Contains aggregated tenant metrics"
      - Key: VantaContainsUserData
        Value: false
