Resources:
  TokenStorageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      AttributeDefinitions:
        # tenantId/token
        - AttributeName: pk
          AttributeType: S
        # tenantId/recipientId
        - AttributeName: gsi1pk
          AttributeType: S
        # tenantId/shard
        - AttributeName: gsi2pk
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
          - AttributeName: gsi1pk
            KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: gsi2
          KeySchema:
          - AttributeName: gsi2pk
            KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Stores requests and messages sent to Courier."
      - Key: VantaContainsUserData
        Value: true
      - Key: tags.courier.com/service
        Value: pipeline
