Resources:
  SendDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
        - AttributeName: gsi2pk
          AttributeType: S
        - AttributeName: gsi2sk
          AttributeType: S
        - AttributeName: gsi3pk
          AttributeType: S
        - AttributeName: gsi3sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
          - AttributeName: gsi1pk
            KeyType: HASH
          - AttributeName: gsi1sk
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi2
          KeySchema:
          - AttributeName: gsi2pk
            KeyType: HASH
          - AttributeName: gsi2sk
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # gsi3 is reserved for the sharded workspace item collections
        # use gsi3 to fetch many Entity by workspaceId
        - IndexName: gsi3
          KeySchema:
          - AttributeName: gsi3pk
            KeyType: HASH
          - AttributeName: gsi3sk
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      # Required for listening to dynamo events
      # StreamSpecification:
      #   StreamViewType: NEW_IMAGE
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Stores send application data model such as client requests and derived entities."
      - Key: VantaContainsUserData
        Value: true
      - Key: tags.courier.com/service
        Value: pipeline
