Resources:
  InboundSegmentEventsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireItems
            Status: Enabled
            ExpirationInDays: 30
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "File storage for inbound segment events"
      - Key: VantaContainsUserData
        Value: true # true if contains user data
      VersioningConfiguration:
        Status: Enabled
