Resources:
  NotesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: VantaOwner
          Value: ${self:custom.vanta.owner}
        - Key: VantaNonProd
          Value: ${self:custom.vanta.nonProd}
        - Key: VantaDescription
          Value: "File storage for notification template notes."
        - Key: VantaContainsUserData
          Value: false
      VersioningConfiguration:
        Status: Enabled
