Resources:
  SendRoutingStrategyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "File storage for log data of our customers API calls."
      - Key: VantaContainsUserData
        Value: true
      VersioningConfiguration:
        Status: Enabled
Outputs:
  SendRoutingStrategyBucketArn:
    Export:
      Name: backend-${self:custom.stage}-SendRoutingStrategyBucketArn
    Value:
      Fn::GetAtt: [SendRoutingStrategyBucket, Arn]
  SendRoutingStrategyBucketName:
    Export:
      Name: backend-${self:custom.stage}-SendRoutingStrategyBucketName
    Value:
      Ref: SendRoutingStrategyBucket
