Resources:
  InboundSegmentEventsKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: 24
      ShardCount: ${self:custom.inboundSegmentEvents.kinesis.${self:custom.stage}.shards, 1}
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Ref: AutoRotatedKmsKey
      Tags:
        - Key: tags.courier.com/elasticity
          Value: fixed
