Resources:
  SqsCheckDeliveryStatus:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      MessageRetentionPeriod: 259200 # 3 Days
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - SqsCheckDeliveryStatusDLQ
            - Arn
        maxReceiveCount: 10
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Queue that contains data necessary to check the status of delivery to a recipient"
      - Key: VantaContainsUserData
        Value: false

  SqsCheckDeliveryStatusDLQ:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      MessageRetentionPeriod: 259200 # 3 Days
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Dead Letter Queue: these queues are used to handle messages that have failed too many times in a primary queue."
      - Key: VantaContainsUserData
        Value: false

  ### Cloudwatch Monitors (only created in production)
  SqsCheckDeliveryStatusAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if queue contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsCheckDeliveryStatus
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing

  SqsCheckDeliveryStatusDLQAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if queue contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsCheckDeliveryStatusDLQ
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing
Outputs:
  SqsCheckDeliveryStatusDLQArn:
    Export:
      Name: backend-${self:custom.stage}-SqsCheckDeliveryStatusDLQArn
    Value:
      Fn::GetAtt: [SqsCheckDeliveryStatusDLQ, Arn]
