Resources:
  SqsUpdateReportedUsage:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - SqsUpdateReportedUsageDLQ
            - Arn
        maxReceiveCount: 10
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Queue for updating reported usage in tenant dynamo DB table"
      - Key: VantaContainsUserData
        Value: false

  SqsUpdateReportedUsageDLQ:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      MessageRetentionPeriod: 1209600
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Dead Letter Queue: these queues are used to handle messages that have failed too many times in a primary queue."
      - Key: VantaContainsUserData
        Value: false

  ### Cloudwatch Monitors (only created in production)
  SqsUpdateReportedUsageAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if queue contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsUpdateReportedUsage
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing

  SqsUpdateReportedUsageDLQAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if queue contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsUpdateReportedUsageDLQ
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing
Outputs:
  SqsUpdateReportedUsageDLQArn:
    Export:
      Name: backend-${self:custom.stage}-SqsUpdateReportedUsageDLQArn
    Value:
      Fn::GetAtt: [SqsUpdateReportedUsageDLQ, Arn]
