Resources:
  SqsBulkJob:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      QueueName: ${self:custom.prefix}-sqs-bulk-job
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - SqsBulkJobDLQ
            - Arn
        maxReceiveCount: 10
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Queuing bulk jobs"
      - Key: VantaContainsUserData
        Value: true
      VisibilityTimeout: 32

  SqsBulkJobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      QueueName: ${self:custom.prefix}-sqs-bulk-job-dlq
      MessageRetentionPeriod: 1209600
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Dead Letter Queue to handle messages that have failed too many times in bulk job queue."
      - Key: VantaContainsUserData
        Value: true

  ### Cloudwatch Monitors (only created in production)
  SqsBulkJobAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if queue contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsBulkJob
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing

  SqsBulkJobDLQAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if queue contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsBulkJobDLQ
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing
Outputs:
  SqsBulkJobDLQArn:
    Export:
      Name: backend-${self:custom.stage}-SqsBulkJobDLQArn
    Value:
      Fn::GetAtt: [SqsBulkJobDLQ, Arn]
