Resources:
  ExperimentsFirehoseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ReplicationConfiguration:
        Role: !GetAtt
          - ExperimentsFirehoseRole
          - Arn
        Rules:
          - Destination:
              Bucket: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ExperimentsFirehoseReplicationBucket
              StorageClass: STANDARD
            Id: Backup
            Prefix: ''
            Status: Enabled
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Data store destination for experiments firehose"
      - Key: VantaContainsUserData
        Value: true
      VersioningConfiguration:
        Status: Enabled

  ExperimentsFirehoseReplicationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - ${self:custom.lifecyclePolicyRules.deleteAfter7Days}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: VantaOwner
          Value: ${self:custom.vanta.owner}
        - Key: VantaNonProd
          Value: ${self:custom.vanta.nonProd}
        - Key: VantaDescription
          Value: "Replication bucket for experiments used by eppo."
        - Key: VantaContainsUserData
          Value: true
      VersioningConfiguration:
        Status: Enabled

  ExperimentsFirehoseRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
                - s3.amazonaws.com

  ExperimentsFirehoseStoragePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ExperimentsFirehoseBucket
                  - /*
          - Action:
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ExperimentsFirehoseBucket
          - Action:
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ExperimentsFirehoseBucket
                  - /*
          - Action:
              - 's3:ReplicateObject'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ExperimentsFirehoseReplicationBucket
                  - /*
      PolicyName: ExperimentsFirehoseStoragePolicy
      Roles:
        - !Ref ExperimentsFirehoseRole

  ExperimentsFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamEncryptionConfigurationInput:
        KeyType: AWS_OWNED_CMK
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: !GetAtt ExperimentsFirehoseBucket.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 10
        CompressionFormat: UNCOMPRESSED
        RoleARN: !GetAtt ExperimentsFirehoseRole.Arn
