Resources:
  EventMapsTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: eventId
          KeyType: RANGE
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  EventMapsTableArn:
    Value:
      Fn::GetAtt: [EventMapsTable, Arn]
  EventMapsTableName:
    Value:
      Ref: EventMapsTable
