Resources:
  ObjectsTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: objtype
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: by-objtype-index
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: objtype
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # Make All columns available in index
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  ObjectsTableArn:
    Value:
      Fn::GetAtt: [ObjectsTable, Arn]
  ObjectsTableName:
    Value:
      Ref: ObjectsTable
