Resources:
  OriginsLookupTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  GlobalOriginLookTableArn:
    Value:
      Fn::GetAtt: [OriginsLookupTable, Arn]
  GlobalOriginLookTableName:
    Value:
      Ref: OriginsLookupTable
