Resources:
  TenantAuthTokensTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: authToken
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: by-tenant-index
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: authToken
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # Make All columns available in index
      KeySchema:
        - AttributeName: authToken
          KeyType: HASH
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  TenantAuthTokensTableArn:
    Value:
      Fn::GetAtt: [TenantAuthTokensTable, Arn]
  TenantAuthTokensTableName:
    Value:
      Ref: TenantAuthTokensTable
