Resources:
  TenantAccessRightsTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: by-tenant-index
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # Make All columns available in index
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: tenantId
          KeyType: RANGE
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  TenantAccessRightsTableArn:
    Value:
      Fn::GetAtt: [TenantAccessRightsTable, Arn]
  TenantAccessRightsTableName:
    Value:
      Ref: TenantAccessRightsTable
