Resources:
  TenantMetricsTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: updated
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: by-updated-index
          KeySchema:
            - AttributeName: updated
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  TenantMetricsTableArn:
    Value:
      Fn::GetAtt: [TenantMetricsTable, Arn]
  TenantMetricsTableName:
    Value:
      Ref: TenantMetricsTable
