Resources:
  TenantsTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
      Replicas:
        - Region: !Ref AWS::Region
        - Region: eu-west-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  TenantsTableArn:
    Value:
      Fn::GetAtt: [TenantsTable, Arn]
  TenantsTableeName:
    Value:
      Ref: TenantsTable
