Resources:
  SqsAutomationStep:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - SqsAutomationStepDLQ
            - Arn
        maxReceiveCount: 10
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Processes automation steps."
      - Key: VantaContainsUserData
        Value: false # true if contains user data

  SqsAutomationStepDLQ:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId:
        Ref: AutoRotatedKmsKey
      Tags:
      - Key: VantaOwner
        Value: ${self:custom.vanta.owner}
      - Key: VantaNonProd
        Value: ${self:custom.vanta.nonProd}
      - Key: VantaDescription
        Value: "Dead Letter Queue: these queues are used to handle messages that have failed too many times in SqsAutomationStep."
      - Key: VantaContainsUserData
        Value: false # true if contains user data

  ### Cloudwatch Monitors (only created in production)
  SqsAutomationStepAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if SqsAutomationStep contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsAutomationStep
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing

  SqsAutomationStepDLQAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions:
        - Ref: AlertEngineeringTopic
      AlarmDescription: "Alarm if SqsAutomationStep contains messages older than 5000 seconds"
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: QueueName
          Value:
            Fn::GetAtt:
              - SqsAutomationStepDLQ
              - QueueName
      EvaluationPeriods: 1
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: "AWS/SQS"
      Period: 900 # 15 minutes (60 * 15)
      Statistic: Average
      Threshold: 5000
      TreatMissingData: missing
Outputs:
  SqsAutomationStepDLQArn:
    Export:
      Name: backend-${self:custom.stage}-SqsAutomationStepDLQArn
    Value:
      Fn::GetAtt: [SqsAutomationStepDLQ, Arn]
